# Generated by Django 4.0.5 on 2022-11-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=20)),
                ('Nazwisko', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('telefon', models.CharField(max_length=11)),
                ('urodzenie', models.DateField()),
                ('pfp', models.ImageField(upload_to=None)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
