# Generated by Django 4.0.5 on 2022-11-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='pfp',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='urodzenie',
        ),
    ]
