# Generated by Django 4.0.5 on 2022-11-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_remove_cv_pfp_remove_cv_urodzenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='data_urodzenia',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='cv',
            name='pfp',
            field=models.ImageField(default='', max_length=1000, upload_to=None),
        ),
    ]
