# Generated by Django 4.0.5 on 2022-11-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_cv_data_urodzenia_cv_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
