# Generated by Django 4.0.5 on 2022-11-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_alter_cv_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='pfp',
        ),
    ]
