# Generated by Django 4.0.5 on 2022-11-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0007_alter_cv_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Pfp',
            field=models.ImageField(blank=True, upload_to='ttt'),
        ),
    ]
