# Generated by Django 4.0.5 on 2022-11-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0008_alter_cv_pfp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='Imie',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='Nazwisko',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='data_urodzenia',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='telefon',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.CharField(choices=[('1', 'Primary'), ('2', 'Secondary'), ('3', 'Higher')], default='2', max_length=10),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='school',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
