# Generated by Django 4.0.5 on 2022-11-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0009_rename_imie_cv_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher', 'Higher')], default='Secondary', max_length=10),
        ),
    ]
